---
title: "HAU Dairy"
logo: "images/nl_agridat_hex_tp.png"
format: dashboard
#server: shiny
date-modified: 2024-03-27
orientation: columns
expandable: false
theme: flatly_edited.scss
embed-resources: true
---

```{r Dashboard set up, echo=FALSE}

source("master_script.R")

```

# Production
## Column {width="35%"}
### Row {height="25%"}
```{r summary boxes}
layout_column_wrap(
  value_box(
    title = h1(HTML("Avg. yield <br>"), latest_comp_year_prod),
    value = latest_yield,
    p(HTML("Litres/day/cow")),
    theme = "teal",
    showcase = NULL,
    showcase_layout = "left center",
    full_screen = TRUE,
    fill = FALSE,
    height = 150L
  ),
  value_box(
    title = h1(HTML("Avg. Protien <br>"), latest_comp_year_prod),
    value = latest_protein,
    p(HTML("%")),
    theme = "teal",
    showcase = NULL,
    showcase_layout = "left center",
    full_screen = TRUE,
    fill = FALSE,
    height = 150L
  ),
  value_box(
    title = h1(HTML("Avg. Butterfat <br>"), latest_comp_year_prod),
    value = latest_fat,
    p(HTML("%")),
    theme = "teal",
    showcase = NULL,
    showcase_layout = "left center",
    full_screen = TRUE,
    fill = FALSE,
    height = 150L
  ),

  width = 1 / 3
)

```

### Row {height="75%"}

```{r leaflet_prod}
map
```

## Graphs {.tabset}


```{r}
#| title: Daily yield per cow
#| fig-cap: The average milk yield produced per cow in the Harper Adams dairy unit for the years 2018 to 2023. The fitted line represents the overall trends of daily milk yield per cow using a LOESS curve plotted using the function y ~ x. Ribbons represent the 95% confidence interval. The average yield per cow is a precalculated variable. 
 yield_per_cow_day_plot
```


```{r}
#| title: Daily protein
daily_protein_plot
#| fig-cap: The daily proportion of protien in milk produced from in the Harper Adams dairy unit for the years 2018 to 2023. The fitted line represents the overall trends of protien proportion using a LOESS curve plotted using the function y ~ x. Ribbons represent the 95% confidence interval. 
```


```{r}
#| title: Daily butterfat
daily_fat_plot
#| fig-cap: The daily proportion of butterfat in milk produced from in the Harper Adams dairy unit for the years 2018 to 2023. The fitted line represents the overall trends of butterfat proportion using a LOESS curve plotted using the function y ~ x. Ribbons represent the 95% confidence interval. 
```



# Fertility and health
## Column {width="35%"}
### Row {height="25%"}
```{r summary boxes fert}
layout_column_wrap(
  value_box(
    title = h1(HTML("Calving events <br>"), latest_comp_year_fert),
    value = tot_calves,
    p(HTML("events")),
    theme = "teal",
    showcase = NULL,
    showcase_layout = "left center",
    full_screen = TRUE,
    fill = FALSE,
    height = 150L
  ),
  value_box(
    title = h1(HTML("Health issues <br>"), latest_comp_year_fert),
    value = tot_health,
    p(HTML("records")),
    theme = "teal",
    showcase = NULL,
    showcase_layout = "left center",
    full_screen = TRUE,
    fill = FALSE,
    height = 150L
  ),
  value_box(
    title = h1(HTML("Herd exits <br>"), latest_comp_year_fert),
    value = tot_exit,
    p(HTML("exits")),
    theme = "teal",
    showcase = NULL,
    showcase_layout = "left center",
    full_screen = TRUE,
    fill = FALSE,
    height = 150L
  ),

  width = 1 / 3
)

```

### Row {height="75%"}

```{r leaflet_fert}
map
```

## Graphs {.tabset}

```{r}
#| title: Fertility events
#| fig-cap: The overall trend of calvings, positive pregnancies and servicing events occuring in the Harper Adams dairy unit for the years 2018 to 2023. The fitted lines represents the overall trends of fertility events using a LOESS curve plotted using the function y ~ x. Ribbons represent the 95% confidence interval. 
fert_events_plot

```

```{r}
#| title: Health issues
#| fig-cap: The total number of health issues recorded each year from the Harper Adams dairy unit from 2018 to 2023. Data is represented using a stacked bar chart with colours representing the quantity of health issue reports for health issues specified in the legend. 

issues_cause_count_plot
```


```{r}
#| title: Herd exits
#| fig-cap: The total number of exits from the Harper Adams dairy herd for each year forthe Harper Adams dairy unit from 2018 to 2023. Data is represented using a stacked bar chart with colours representing the different reasons for herd exits as specified in the legend. 

exit_count_plot
```

# Stock take
## Column {width="35%"}
### Row {height="25%"}
```{r summary boxes_st}
layout_column_wrap(
  value_box(
    title = h1(HTML("Avg. in milk <br>"), latest_comp_year_st),
    value = tot_in_milk_latest,
      p(HTML("cows")),
    theme = "teal",
    showcase = NULL,
    showcase_layout = "left center",
    full_screen = TRUE,
    fill = FALSE,
    height = 150L
  ),
  value_box(
    title = h1(HTML("Avg. in tank <br>"), latest_comp_year_st),
    value = tot_in_tank_latest,
    p(HTML("cows")),
    theme = "teal",
    showcase = NULL,
    showcase_layout = "left center",
    full_screen = TRUE,
    fill = FALSE,
    height = 150L
  ),
  value_box(
    title = h1(HTML("Avg. dry <br>"), latest_comp_year_st),
    value = tot_dry_lastest,
     p(HTML("cows")),
    theme = "teal",
    showcase = NULL,
    showcase_layout = "left center",
    full_screen = TRUE,
    fill = FALSE,
    height = 150L
  ),

  width = 1 / 3
)

```

### Row {height="75%"}

```{r leaflet_st}
map
```


## Graphs {.tabset}

```{r}
#| title: Stock take - Milk status
#| fig-cap: The total number of cows in the Harper Adams dairy unit that were recorded as in milk, in tank or dry. The fitted line represents the overall trends of cow milk status using LOESS curves plotted using the function y ~ x. Ribbons represent the 95% confidence interval. 
stock_take_graph
```

# Data

## Column {.tabset width="70%"}

```{r}
#| title: Production

datatable(prod_data, filter = list(position = 'topleft', clear = FALSE),
          extensions = 'Buttons',
          options = list(dom = 'Bfrtip',
                         buttons = c('copy')))

```

```{r}
#| title: Fertility and Health 

datatable(fert_health_data, filter = list(position = 'topleft', clear = FALSE),
          extensions = 'Buttons',
          options = list(dom = 'Bfrtip',
                         buttons = c('copy')))

```

```{r}
#| title: Stock take 
datatable(stock_take_data, filter = list(position = 'topleft', clear = FALSE),
          extensions = 'Buttons',
          options = list(dom = 'Bfrtip',
                         buttons = c('copy')))

```

## Column {width="30%"}

### Row {height="25%"}

::: {.card title="Download the data"}
[Download excel file](https://github.com/HADairy/dairy_dash/raw/main/HA_dairy_master.xlsx)

:::

### Row {.tabset height="75%"}

::: {.card title="Information"}
ADD DATA INFORMATION HERE

**Comments**

ADD ANY DATA COMMENTS HERE
:::